FROM golang:alpine AS builder

ARG InstallFolder=/go/src/github.com/ajaxe/mc-manager

RUN mkdir -p $InstallFolder

WORKDIR $InstallFolder

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ENV GOCACHE=/root/.cache/go-build

RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=cache,target="/root/.cache/go-build" \
    --mount=type=bind,target=. \
    GOARCH=wasm GOOS=js go build -o /root/app/web/app.wasm ./cmd/webapp \
    && go build -o /root/app/server ./cmd/webapp/ \
    && cp -a ./web/* /root/app/web/

CMD ["go", "test", "-v", "./internal/gameserver"]
